version: "3"
services:
  backend_1:
    container_name: backend_1
    build:
      context: .
      dockerfile: /home/eliud1013/Proyectos-Escuela/ProFeCo/Dockerfile
    environment:
      - DB_HOST=backend_db
      - DB_USER=root
      - DB_PASSWORD=12345
      - DB=Profeco
      - SECRET=958db6d9d22a47e980ba2c6228552edb
  backend_2:
    container_name: backend_2
    build:
      context: .
      dockerfile: /home/eliud1013/Proyectos-Escuela/ProFeCo/Dockerfile
    environment:
      - DB_HOST=backend_db
      - DB_USER=root
      - DB_PASSWORD=12345
      - DB=Profeco
      - SECRET=958db6d9d22a47e980ba2c6228552edb
  db:
    container_name: backend_db
    image: mariadb:latest
    environment:
      - MARIADB_ROOT_PASSWORD=12345
    volumes:
      - profeco_db_data:/var/lib/mysql
  web_server:
    container_name: profeco_nginx
    image: nginx:latest
    ports:
      - 3000:80
    volumes:
      - /home/eliud1013/Proyectos-Escuela/ProFeCo/nginx.conf:/etc/nginx/nginx.conf

volumes:
  profeco_db_data:
    external: true
