version: "3"
services:
  backend_1:
    build:
      context: .
      dockerfile: /home/eliud1013/Proyectos-Escuela/ProFeCo/Dockerfile
    ports:
      - 3001:3000
    environment:
      - DB_HOST=mariadb
      - DB_USER=root
      - DB_PASSWORD=12345
      - DB=Profeco
      - SECRET=958db6d9d22a47e980ba2c6228552edb
  backend_2:
    build:
      context: .
      dockerfile: /home/eliud1013/Proyectos-Escuela/ProFeCo/Dockerfile
    ports:
      - 3002:3000
    environment:
      - DB_HOST=mariadb
      - DB_USER=root
      - DB_PASSWORD=12345
      - DB=Profeco
      - SECRET=958db6d9d22a47e980ba2c6228552edb
  db:
    image: mariadb:latest
    container_name: mariadb
    ports:
      - 3306:3306
    environment:
      - MARIADB_ROOT_PASSWORD=12345
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data:
