

DROP DATABASE Profeco;
CREATE DATABASE Profeco;
USE Profeco;


CREATE TABLE Clientes(
    clienteId VARCHAR(52) PRIMARY KEY NOT NULL UNIQUE,
    name VARCHAR(52) NOT NULL,
    username VARCHAR(52) NOT NULL,
    email VARCHAR(52) NOT NULL UNIQUE,
    password VARCHAR(52) NOT NULL,
    genre ENUM('H','M') NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP

);


CREATE TABLE Mercados(
    mercadoId VARCHAR(52) PRIMARY KEY NOT NULL,
    mercado VARCHAR(52) NOT NULL,
    adminUser VARCHAR(52) NOT NULL UNIQUE,
    password VARCHAR(52) NOT NULL,
    email VARCHAR(52) NOT NULL UNIQUE,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP

);

CREATE TABLE ProfecoUsuario(
    profecoUserId VARCHAR(52) PRIMARY KEY NOT NULL UNIQUE,
    username VARCHAR(52) NOT NULL UNIQUE,
    password VARCHAR(52) NOT NULL,
    email VARCHAR(52) NOT NULL UNIQUE,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);